//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiResiliencia.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiResiliencia.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After protection.
        /// </summary>
        public static string AfterChange {
            get {
                return ResourceManager.GetString("AfterChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before protection.
        /// </summary>
        public static string BeforeChange {
            get {
                return ResourceManager.GetString("BeforeChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string BenutzernameLabel {
            get {
                return ResourceManager.GetString("BenutzernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of vehicles / day.
        /// </summary>
        public static string CarsPerDay {
            get {
                return ResourceManager.GetString("CarsPerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Successfully changed Password&lt;/strong&gt;.
        /// </summary>
        public static string ChangePasswordSuccess {
            get {
                return ResourceManager.GetString("ChangePasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose project.
        /// </summary>
        public static string ChooseProject {
            get {
                return ResourceManager.GetString("ChooseProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to upload all Shapefile-Files.
        /// </summary>
        public static string ClickHereForUploading {
            get {
                return ResourceManager.GetString("ClickHereForUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click on an object for more information.
        /// </summary>
        public static string ClickOnAnObject {
            get {
                return ResourceManager.GetString("ClickOnAnObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close project.
        /// </summary>
        public static string Close_Project {
            get {
                return ResourceManager.GetString("Close Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companymanager.
        /// </summary>
        public static string Companymanager {
            get {
                return ResourceManager.GetString("Companymanager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction Costs.
        /// </summary>
        public static string Construction_Costs {
            get {
                return ResourceManager.GetString("Construction Costs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction costs [Bs].
        /// </summary>
        public static string ConstructionCosts {
            get {
                return ResourceManager.GetString("ConstructionCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinates.
        /// </summary>
        public static string Coordinates {
            get {
                return ResourceManager.GetString("Coordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy from &quot;Before Measurement&quot;.
        /// </summary>
        public static string CopyFromBefore {
            get {
                return ResourceManager.GetString("CopyFromBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Rate [%] for NPV.
        /// </summary>
        public static string DiscountRate {
            get {
                return ResourceManager.GetString("DiscountRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPI.
        /// </summary>
        public static string dpi {
            get {
                return ResourceManager.GetString("dpi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw.
        /// </summary>
        public static string Draw {
            get {
                return ResourceManager.GetString("Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DrawDelete {
            get {
                return ResourceManager.GetString("DrawDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string DrawModify {
            get {
                return ResourceManager.GetString("DrawModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string DrawNew {
            get {
                return ResourceManager.GetString("DrawNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw object.
        /// </summary>
        public static string DrawObject {
            get {
                return ResourceManager.GetString("DrawObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Users.
        /// </summary>
        public static string Existing_Users {
            get {
                return ResourceManager.GetString("Existing Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing intensity maps.
        /// </summary>
        public static string ExistingIK {
            get {
                return ResourceManager.GetString("ExistingIK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Companies.
        /// </summary>
        public static string Exitsting_Companies {
            get {
                return ResourceManager.GetString("Exitsting Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export as PDF.
        /// </summary>
        public static string ExportAsPDF {
            get {
                return ResourceManager.GetString("ExportAsPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export as GPKG.
        /// </summary>
        public static string ExportProject {
            get {
                return ResourceManager.GetString("ExportProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fast.
        /// </summary>
        public static string fast {
            get {
                return ResourceManager.GetString("fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of floors.
        /// </summary>
        public static string Floors {
            get {
                return ResourceManager.GetString("Floors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danger analysis.
        /// </summary>
        public static string Gefahrenanalyse {
            get {
                return ResourceManager.GetString("Gefahrenanalyse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensity class.
        /// </summary>
        public static string IKClasses {
            get {
                return ResourceManager.GetString("IKClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload import file. Geopakage files are possible. For a valid data model it is recommended to make an export of the project first and to edit or complete this data..
        /// </summary>
        public static string ImportMessage {
            get {
                return ResourceManager.GetString("ImportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import SHP.
        /// </summary>
        public static string ImportShp {
            get {
                return ResourceManager.GetString("ImportShp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensity degree.
        /// </summary>
        public static string Intensitaetsstufe {
            get {
                return ResourceManager.GetString("Intensitaetsstufe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensity maps.
        /// </summary>
        public static string IntensityMaps {
            get {
                return ResourceManager.GetString("IntensityMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string LayerDisplay {
            get {
                return ResourceManager.GetString("LayerDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string LayerLabel {
            get {
                return ResourceManager.GetString("LayerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available layers.
        /// </summary>
        public static string LayerLayers {
            get {
                return ResourceManager.GetString("LayerLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layers.
        /// </summary>
        public static string Layers {
            get {
                return ResourceManager.GetString("Layers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lifespan [years].
        /// </summary>
        public static string LifeSpan {
            get {
                return ResourceManager.GetString("LifeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading content. Please wait....
        /// </summary>
        public static string LoadingMessage {
            get {
                return ResourceManager.GetString("LoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Costs.
        /// </summary>
        public static string MaintenanceCosts {
            get {
                return ResourceManager.GetString("MaintenanceCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export map.
        /// </summary>
        public static string MapExport {
            get {
                return ResourceManager.GetString("MapExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to medium.
        /// </summary>
        public static string mittel {
            get {
                return ResourceManager.GetString("mittel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivation to change presence.
        /// </summary>
        public static string MotivationToChangePerson {
            get {
                return ResourceManager.GetString("MotivationToChangePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivation to change value.
        /// </summary>
        public static string MotivationToChnageValue {
            get {
                return ResourceManager.GetString("MotivationToChnageValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click or drag your logo here.
        /// </summary>
        public static string Move_logo_here {
            get {
                return ResourceManager.GetString("Move logo here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural hazard.
        /// </summary>
        public static string NatHaz {
            get {
                return ResourceManager.GetString("NatHaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Company.
        /// </summary>
        public static string New_Company {
            get {
                return ResourceManager.GetString("New Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User.
        /// </summary>
        public static string New_User {
            get {
                return ResourceManager.GetString("New User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project.
        /// </summary>
        public static string NewProject {
            get {
                return ResourceManager.GetString("NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of object.
        /// </summary>
        public static string ObjectName {
            get {
                return ResourceManager.GetString("ObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object.
        /// </summary>
        public static string Objekt {
            get {
                return ResourceManager.GetString("Objekt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating costs.
        /// </summary>
        public static string OperatingCosts {
            get {
                return ResourceManager.GetString("OperatingCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operational Costs      .
        /// </summary>
        public static string Operational_Costs {
            get {
                return ResourceManager.GetString("Operational Costs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All hazards without drought.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswortLabel {
            get {
                return ResourceManager.GetString("PasswortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presence of persons.
        /// </summary>
        public static string PersonPerFloor {
            get {
                return ResourceManager.GetString("PersonPerFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presence of persons.
        /// </summary>
        public static string PersonPresence {
            get {
                return ResourceManager.GetString("PersonPresence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        public static string Plan {
            get {
                return ResourceManager.GetString("Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose project.
        /// </summary>
        public static string PleaseChooseProject {
            get {
                return ResourceManager.GetString("PleaseChooseProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powerd by.
        /// </summary>
        public static string PowerdBy {
            get {
                return ResourceManager.GetString("PowerdBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pra.
        /// </summary>
        public static string Pra {
            get {
                return ResourceManager.GetString("Pra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heading.
        /// </summary>
        public static string PrintHeading {
            get {
                return ResourceManager.GetString("PrintHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print map.
        /// </summary>
        public static string PrintMap {
            get {
                return ResourceManager.GetString("PrintMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size.
        /// </summary>
        public static string PrintPageSize {
            get {
                return ResourceManager.GetString("PrintPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Overview.
        /// </summary>
        public static string ProjectDefinition {
            get {
                return ResourceManager.GetString("ProjectDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Manager.
        /// </summary>
        public static string ProjectManager {
            get {
                return ResourceManager.GetString("ProjectManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Project not found.
        /// </summary>
        public static string ProjectNotFound {
            get {
                return ResourceManager.GetString("ProjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Number.
        /// </summary>
        public static string ProjectNumber {
            get {
                return ResourceManager.GetString("ProjectNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perimeter.
        /// </summary>
        public static string ProjectPerimeter {
            get {
                return ResourceManager.GetString("ProjectPerimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project state.
        /// </summary>
        public static string ProjectState {
            get {
                return ResourceManager.GetString("ProjectState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate of Return.
        /// </summary>
        public static string RateofReturn {
            get {
                return ResourceManager.GetString("RateofReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalculate.
        /// </summary>
        public static string Recalculate {
            get {
                return ResourceManager.GetString("Recalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resilience.
        /// </summary>
        public static string Resilienz {
            get {
                return ResourceManager.GetString("Resilienz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string Resultate {
            get {
                return ResourceManager.GetString("Resultate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claims potential.
        /// </summary>
        public static string Schadenpotential {
            get {
                return ResourceManager.GetString("Schadenpotential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protection.
        /// </summary>
        public static string Schutzmassnahme {
            get {
                return ResourceManager.GetString("Schutzmassnahme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected object.
        /// </summary>
        public static string SelectedObject {
            get {
                return ResourceManager.GetString("SelectedObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the goal:.
        /// </summary>
        public static string SelectGoal {
            get {
                return ResourceManager.GetString("SelectGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Session expired, please reload page.
        /// </summary>
        public static string SessionOut {
            get {
                return ResourceManager.GetString("SessionOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Result.
        /// </summary>
        public static string Show_Result {
            get {
                return ResourceManager.GetString("Show Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Errors on map.
        /// </summary>
        public static string ShowErrorsOnMap {
            get {
                return ResourceManager.GetString("ShowErrorsOnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to slow.
        /// </summary>
        public static string slow {
            get {
                return ResourceManager.GetString("slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strong.
        /// </summary>
        public static string strong {
            get {
                return ResourceManager.GetString("strong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unity of object.
        /// </summary>
        public static string UnityOfObject {
            get {
                return ResourceManager.GetString("UnityOfObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading following files.
        /// </summary>
        public static string UploadingFiles {
            get {
                return ResourceManager.GetString("UploadingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Userinformation.
        /// </summary>
        public static string UserInformation {
            get {
                return ResourceManager.GetString("UserInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usermanger.
        /// </summary>
        public static string Usermanager {
            get {
                return ResourceManager.GetString("Usermanager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Userprofile.
        /// </summary>
        public static string UserProfile {
            get {
                return ResourceManager.GetString("UserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Added Tax [%].
        /// </summary>
        public static string ValueAddedTax {
            get {
                return ResourceManager.GetString("ValueAddedTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual value / unit [Bs].
        /// </summary>
        public static string ValuePerUnity {
            get {
                return ResourceManager.GetString("ValuePerUnity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average speed.
        /// </summary>
        public static string Velocity {
            get {
                return ResourceManager.GetString("Velocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings.
        /// </summary>
        public static string Warnings {
            get {
                return ResourceManager.GetString("Warnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weak.
        /// </summary>
        public static string weak {
            get {
                return ResourceManager.GetString("weak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
    }
}
